apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "formaTAPIRest.fullname" . }}
  labels:
    {{- include "formaTAPIRest.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "formaTAPIRest.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "formaTAPIRest.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "formaTAPIRest.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: TAPIR_RUNNER
              value: "kubernetes"
          command: ["/bin/sh", "-c", "pip3 install pykube-ng ; sleep 9999"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: conversion
            mountPath: /data
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /formaTAPIRest/v1/openapi.json
              port: http
          readinessProbe:
            httpGet:
              path: /formaTAPIRest/v1/openapi.json
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
{{- if .Values.persistence.enabled }}
        - name: conversion
          persistentVolumeClaim:
{{- if .Values.persistence.existingClaim }}
{{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else }}
            claimName: pvc-conversion
{{- end }}
{{- else if not .Values.persistence.enabled }}
        - name: conversion
          emptyDir: {}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
