apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PersistentVolumeClaim.name }}
  namespace: {{ .Values.app.namespace | default "default" }}
spec:
  storageClassName: {{ .Values.PersistentVolumeClaim.storageclass }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.size }}