{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{ if .Values.app.namespace }}
  namespace: {{ .Values.app.namespace }}
  {{ else }}
  namespace: "default"
  {{ end }}
{{ end }}
